# Generated by Django 3.0.4 on 2020-03-28 15:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default=django.utils.timezone.now, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
