# Generated by Django 3.0.4 on 2020-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
